### PR TITLE
fix: do not accumulate if pod is not there anymore #333

### LINKED ISSUE #333: agent is restarting when pod is not found
https://github.com/honeycombio/honeycomb-kubernetes-agent/blob/66864979093c63a6dc423f435633b553a77d4e40/metrics/metadata.go#L52

this error is not handled gracefully.
We checked one pod ids and it was a CI runner that was done with the job.

```
level=error msg="Metadata: Pod not found" podUid=2fd21870-xxxx-xxxx-xxxx-4eea5b905015
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa89ce9]
```

### PR DESCRIPTION
**Pull request by enc**
## Which problem is this PR solving?

- Accumulator is trying to pull metrics for pods that do not exist.

## Short description of the changes

- also abort accumulation if no pod data is available any more.

Fixes #333

### CODE REVIEW

File: metrics/accumulator.go [hunk 1]
```diff
@@ -59,6 +59,12 @@ func (a *MetricDataAccumulator) podStats(podResource *Resource, s stats.PodStats
 	if !a.metricGroupsToCollect[PodMetricGroup] {
 		return
 	}
+	
+	// Metatdata can be nil if pod is terminted before metodata is fetched.
```
Comment (TylerHelmuth) [inline metrics/accumulator.go:63]:
```suggestion
	// Metatdata can be nil if pod is terminated before metadata is fetched.
```

**Review by TylerHelmuth — APPROVED** [review]
One nit, otherwise LGTM.  Thanks for taking care of this!
