### PR TITLE
fix: check for existence of optional CPU stats to prevent exceptions

### LINKED ISSUE #204: CrashLoopBackOff on nil pointer deref
**Versions**
2.2.1

**Steps to reproduce**

1. Unclear - but I've seen this twice today in dogfood, on different pods.

```
time="2021-12-29T18:20:04Z" level=info msg="Done tailing file" filePath=/var/log/pods/honeycomb-dogfood_basset-27346685-x7ztx_b9bf7535-88e7-486d-b60a-0ab718c596bd/basset/0.log
time="2021-12-29T18:21:00Z" level=info msg="Setting up watcher for pod" Name=basset-27346701-tz9hl UID=7b52bcb8-975c-4bc4-b277-ad3af9b98e1d
time="2021-12-29T18:21:00Z" level=info msg="starting watcher for pod" labelselector="app,app!=honeycomb-agent" name=basset-27346701-tz9hl namespace=honeycomb-dogfood uid=7b52bcb8-975c-4bc4-b277-ad3af9b98e1d
time="2021-12-29T18:21:02Z" level=info msg="Log pattern" log pattern="/var/log/pods/honeycomb-dogfood_basset-27346701-tz9hl_7b52bcb8-975c-4bc4-b277-ad3af9b98e1d/*/*"
time="2021-12-29T18:21:02Z" level=info msg="Initializing file handler" parser=nop path=/var/log/pods/honeycomb-dogfood_basset-27346701-tz9hl_7b52bcb8-975c-4bc4-b277-ad3af9b98e1d/basset/0.log
time="2021-12-29T18:21:02Z" level=info msg="no prior tail state found" detail="key not found" path=/var/log/pods/honeycomb-dogfood_basset-27346701-tz9hl_7b52bcb8-975c-4bc4-b277-ad3af9b98e1d/basset/0.log
time="2021-12-29T18:21:02Z" level=info msg="Tailing file" offset=0 path=/var/log/pods/honeycomb-dogfood_basset-27346701-tz9hl_7b52bcb8-975c-4bc4-b277-ad3af9b98e1d/basset/0.log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x64c5a4]

goroutine 65 [running]:
github.com/honeycombio/honeycomb-kubernetes-agent/metrics.getPodResource(0x400057c140, 0x4000b0f320, 0x12, 0x4000b0f338, 0x11, 0x4000b9e2a0, 0x24, 0x0, 0xed95e9e0c, 0x1819560, ...)
	/home/circleci/project/metrics/resource.go:55 +0x2a4
github.com/honeycombio/honeycomb-kubernetes-agent/metrics.(*Processor).GenerateMetricsData(0x4000b8a070, 0x4002452000, 0x4000c0b4a0, 0x4000ae5620, 0x1, 0xa2c7d202020200a, 0x6d656d2220202020)
	/home/circleci/project/metrics/processor.go:41 +0x25c
github.com/honeycombio/honeycomb-kubernetes-agent/service.(*runnable).Run(0x40001cfd50, 0x400298bc10, 0x1)
	/home/circleci/project/service/runnable.go:82 +0x3c4
github.com/honeycombio/honeycomb-kubernetes-agent/interval.(*Runner).run(0x4000a72f40, 0x0, 0x0)
	/home/circleci/project/interval/interval_runner.go:72 +0xa4
github.com/honeycombio/honeycomb-kubernetes-agent/interval.(*Runner).Start(0x4000a72f40, 0x0, 0x0)
	/home/circleci/project/interval/interval_runner.go:50 +0x1e4
github.com/honeycombio/honeycomb-kubernetes-agent/service.(*Service).Start.func1(0x40001cfb90)
	/home/circleci/project/service/service.go:138 +0x2c
created by github.com/honeycombio/honeycomb-kubernetes-agent/service.(*Service).Start
	/home/circleci/project/service/service.go:137 +0x458
```

**Additional context**

### PR DESCRIPTION
**Pull request by JamieDanielson**
## Which problem is this PR solving?

- fixes #204 

## Short description of the changes

- check for CPUStats because it's an optional field. In the issue reported, an error was thrown on `s.CPU.Time.Time`. Though `Time` is a required field on the `CPUStats` struct, the `CPUStats` are optional on the `NodeStats` struct. We can check for existence of CPUStats and only add if it exists.
- This PR checks for existence of CPU, as well as optional fields on CPUStats
- Current tests checked for proper handling of CPU Stats when available, but did not check for proper handling of omitted CPU Stats. I updated the second pod in `stats-summary.json` to have no CPU Stats, and added test to assert against it. 
- Other similar scenarios (volume, fs, etc) will be addressed in a separate PR.

### CODE REVIEW

File: metrics/processor.go [hunk 1]
```diff
@@ -122,9 +122,15 @@ func (p *Processor) UptimeMetrics(startTime time.Time) Metrics {
...
 
 func (p *Processor) CpuMetrics(s *stats.CPUStats, limit float64) Metrics {
+	if s == nil {
+		return nil
+	}
 	// Convert nanoCores to seconds
 	var cpuUsage float64
-	nanoCores := s.UsageNanoCores
+	var nanoCores *uint64
+	if s.UsageNanoCores != nil {
```
Comment (vreynolds) [inline metrics/processor.go:131]: Is this null-check strictly necessary, if we check for null `nanoCores` below?

File: metrics/resource.go [hunk 2]
```diff
@@ -21,21 +21,24 @@ func getNodeResource(s stats.NodeStats, metadata *Metadata) *Resource {
...
 
+	resource := &Resource{
+		Type:   "node",
+		Name:   s.NodeName,
+		Labels: labels,
+	}
+	if s.CPU != nil {
+		resource.Timestamp = s.CPU.Time.Time
+	}
 	if metadata.IncludeNodeLabels {
```
Comment (vreynolds) [inline metrics/resource.go:32]: Can this `labels` creation go above the resource creation, where `labels` are used? I think it will work either way, but feels out of order now.

File: metrics/resource.go [hunk 3]
```diff
@@ -21,21 +21,24 @@ func getNodeResource(s stats.NodeStats, metadata *Metadata) *Resource {
 		LabelNodeName: s.NodeName,
 	}
 
+	resource := &Resource{
+		Type:   "node",
+		Name:   s.NodeName,
+		Labels: labels,
+	}
+	if s.CPU != nil {
+		resource.Timestamp = s.CPU.Time.Time
```
Comment (vreynolds) [inline metrics/resource.go:30]: Do we know what happens when we don't set the timestamp?

File: metrics/processor.go (hunk 1 above)
Comment (JamieDanielson) [reply metrics/processor.go:131]: Unsure. My concern was that setting `nanoCores` equal to `s.UsageNanoCores` would throw an exception if `s.UsageNanoCores` doesn't exist.

File: metrics/resource.go (hunk 2 above)
Comment (JamieDanielson) [reply metrics/resource.go:30]: I just added a new commit that moves the `labels` section above `Timestamp`.  I think the original creation of `resource` needs to happen before the `if` block, because `labels` includes `LabelNodeName: s.NodeName` at that point, but may not get more.

File: metrics/processor.go (hunk 1 above)
Comment (vreynolds) [reply metrics/processor.go:131]: That should be fine. The assignment will just result in `nanoCores` being `nil`.

**Review by MikeGoldsmith — APPROVED** [review]

File: metrics/resource.go (hunk 3 above)
Comment (JamieDanielson) [reply metrics/resource.go]: Based on our conversation yesterday, looks like it sets the timestamp on the event based on the resource timestamp [`ev.Timestamp = res.Timestamp`](https://github.com/honeycombio/honeycomb-kubernetes-agent/blob/c062f64c5db08c9668459f81fc089c2fa494d230/service/runnable.go#L177)  using libhoney in `runnable.go`. In that case there's likely a timestamp set on ingest.

Is it better to have an else clause here so a timestamp still exists, setting the Timestamp equal to the start time on the pod, node, etc?

```go
	if s.CPU != nil {
		resource.Timestamp = s.CPU.Time.Time
	} else {
		resource.Timestamp = s.StartTime.Time
	}
```

Comment (JamieDanielson) [reply metrics/resource.go]: Oh actually, looks like `Timestamp` is optional to set the time for the event, and otherwise [defaults to `time.Now()`](https://github.com/honeycombio/libhoney-go/blob/v1.15.8/libhoney.go#L891). So either way this should be okay to omit the timestamp unless we think it's better to have something.

For some additional testing I also curled the events endpoint with a true Timestamp `"X-Honeycomb-Event-Time: 2022-01-07T20:47:26.794Z"` and an empty Timestamp `"X-Honeycomb-Event-Time: "` and the empty time used server ingest time.

Comment (vreynolds) [reply metrics/resource.go]: I wonder if @puckpuck has an opinion here, as the OG author 😉
